id: P001755
initial_creation_type: ocr
source_metadata:
  id: bdr:W1GS54749
  title: བསྐལ་པ་བཟང་པོའི་སངས་རྒྱས་རྣམས་ལ་མཆོད་ཅིང་གསོལ་བ་གདབ་པའི་ཆོ་ག་བྱིན་རླབས་གྲུ་ཆར་འཇོ་བར་བྱེད་པའི་དབྱར་གྱི་རྔ་གསང
  author: ''
  volumes:
    8b8eda14fdfa4a6eae1179c05d10a9ca:
      image_group_id: I1GS54856
      title: ''
      volume_number: 1
      total_pages: 122
      base_file: v001.txt
