id: opecha:P001755
initial_creation_type: ocr
source_metadata:
  id: bdr:W1GS54749
  title: བསྐལ་པ་བཟང་པོའི་སངས་རྒྱས་རྣམས་ལ་མཆོད་ཅིང་གསོལ་བ་གདབ་པའི་ཆོ་ག་བྱིན་རླབས་གྲུ་ཆར་འཇོ་བར་བྱེད་པའི་དབྱར་གྱི་རྔ་གསང
  volume: ''
  author: ''
