id: ID18B10F7
legacy_id: P001755
ocr_import_info:
  bdrc_scan_id: W1GS54749
  source: bdrc
  ocr_info:
    timestamp: '2020-03-26T09:48:19'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-08-30T20:05:08.282374+00:00'
last_modified: 2022-08-31 04:05:22.159340
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W1GS54749
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW1GS54749
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: བསྐལ་པ་བཟང་པོའི་སངས་རྒྱས་རྣམས་ལ་མཆོད་ཅིང་གསོལ་བ་གདབ་པའི་ཆོ་ག་བྱིན་རླབས་གྲུ་ཆར་འཇོ་བར་བྱེད་པའི་དབྱར་གྱི་རྔ་གསང་།
  author: ཨ་ལག་ཤ་ལྷ་བཙུན་བློ་བཟང་བསྟན་པའི་མགོན་པོ།
statistics:
  ocr_word_mean_confidence_index: 0.6130494262399612
  ocr_word_median_confidence_index: 0.6700000166893005
quality: null
bases:
  I1GS54856:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1GS54856
      total_pages: 122
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1GS54856.txt
    statistics:
      ocr_word_median_confidence_index: 0.6700000166893005
      ocr_word_mean_confidence_index: 0.6130494262399612
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
