id: ID18B10F7
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-26T09:49:10+00:00'
last_modified: '2022-06-07T15:00:35.493349+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1GS54749
  title: བསྐལ་པ་བཟང་པོའི་སངས་རྒྱས་རྣམས་ལ་མཆོད་ཅིང་གསོལ་བ་གདབ་པའི་ཆོ་ག་བྱིན་རླབས་གྲུ་ཆར་འཇོ་བར་བྱེད་པའི་དབྱར་གྱི་རྔ་གསང
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    ADF5:
      image_group_id: I1GS54856
      title: ''
      total_pages: 122
      order: 1
      base_file: ADF5.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
